We begin by importing PyTorch:

In [1]:
import torch

/home/exponential/.local/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


## Tensors

At its core, PyTorch is a library for processing tensors. A tensor is a number, vector, matrix or any n-dimensional array. Let's create a tensor with a single number:

In [ ]:
# Tensor : any dimension 
# zero dimensions : number
# one  dimensions : vector
# two  dimensions : matrix
# three dimensions : tensor

# Deep learning me jobhe computation krte hai wo ,deep learning k upper ki jate hai


In [3]:
# Number : zero dimenstions
t1 = torch.tensor(4.) # 4.0 is argument or input
# 4. means floating point number
t1

tensor(4.)

`4.` is a shorthand for `4.0`. It is used to indicate to Python (and PyTorch) that you want to create a floating point number. We can verify this by checking the `dtype` attribute of our tensor:

In [4]:
t1.dtype

torch.float32

In [5]:
a2 = torch.tensor(4)
a2.dtype

torch.int64

Let's try creating slightly more complex tensors:

In [6]:
# Vector : 1D 
t2 = torch.tensor([1., 2, 3, 4]) # if any floating point ,then all floating point
t2

tensor([1., 2., 3., 4.])

In [ ]:
# Matrix : 2 D  
t3 = torch.tensor([[5., 6], # here 2 rows ,3 columns
                   [7, 8], 
                   [9, 10]])
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [7]:
# 3-dimensional array : vizualize as matrix k peeche ek matrix rakha hua hai (LOL screeb 2D hai)
t4 = torch.tensor([
    [[11, 12, 13], 
     [13, 14, 15]], 
    [[15, 16, 17], 
     [17, 18, 19.]]])
t4

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])

Tensors can have any number of dimensions, and different lengths along each dimension. We can inspect the length along each dimension using the `.shape` property of a tensor.

In [8]:
print(t1)
t1.shape # shape -> elements and dimension 

tensor(4.)


torch.Size([])

In [9]:
print(t2)
t2.shape

tensor([1., 2., 3., 4.])


torch.Size([4])

In [ ]:
print(t3)
t3.shape

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])


torch.Size([3, 2])

In [ ]:
print(t4)
t4.shape

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])


torch.Size([2, 2, 3])

In [15]:
# Error : same (dimension/data type) hone chahie sabke

t4 = torch.tensor([
    [[11, 12, 13 , 22], 
     [13, 14, 15]], 
    [[15, 16, 17], 
     [17, 18, 19.]]])

t4


ValueError: expected sequence of length 4 at dim 2 (got 3)

## Tensor operations and gradients

We can combine tensors with the usual arithmetic operations. Let's look an example:

In [ ]:
# One of the benefit of pytorch is that we can do arithematic operation on tensor like a number

In [16]:
# Create tensors.
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True) # requires_grad=True : means iska derivative calculate krke rakho
b = torch.tensor(5., requires_grad=True) # grad means (gradient/derivative)
x, w, b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

We've created 3 tensors `x`, `w` and `b`, all numbers. `w` and `b` have an additional parameter `requires_grad` set to `True`. We'll see what it does in just a moment. 

Let's create a new tensor `y` by combining these tensors:

In [20]:
# Arithmetic operations
y = w * x + b
y 
# y ka derivate w k sath ,y ka derivate x k sath , y ka derivate b k sath  
# pytorch ye derivate apne aap calculate krdeta hai

tensor(17., grad_fn=<AddBackward0>)

As expected, `y` is a tensor with the value `3 * 4 + 5 = 17`. What makes PyTorch special is that we can automatically compute the derivative of `y` w.r.t. the tensors that have `requires_grad` set to `True` i.e. w and b. To compute the derivatives, we can call the `.backward` method on our result `y`.

In [21]:
# Compute derivatives
y.backward()

The derivates of `y` w.r.t the input tensors are stored in the `.grad` property of the respective tensors.

In [22]:
# Display gradients
print('dy/dx:', x.grad) # grad means (gradient/derivative)
print('dy/dw:', w.grad)
print('dy/db:', b.grad)

dy/dx: None
dy/dw: tensor(6.)
dy/db: tensor(3.)


As expected, `dy/dw` has the same value as `x` i.e. `3`, and `dy/db` has the value `1`. Note that `x.grad` is `None`, because `x` doesn't have `requires_grad` set to `True`. 

The "grad" in `w.grad` stands for gradient, which is another term for derivative, used mainly when dealing with matrices. 

## Interoperability with Numpy

[Numpy](http://www.numpy.org/) is a popular open source library used for mathematical and scientific computing in Python. It enables efficient operations on large multi-dimensional arrays, and has a large ecosystem of supporting libraries:

* [Matplotlib](https://matplotlib.org/) for plotting and visualization
* [OpenCV](https://opencv.org/) for image and video processing
* [Pandas](https://pandas.pydata.org/) for file I/O and data analysis

Instead of reinventing the wheel, PyTorch interoperates really well with Numpy to leverage its existing ecosystem of tools and libraries.

Here's how we create an array in Numpy:

In [ ]:
import numpy as np

x = np.array([[1, 2], [3, 4.]])
x

array([[1., 2.],
       [3., 4.]])

We can convert a Numpy array to a PyTorch tensor using `torch.from_numpy`.

In [ ]:
# Convert the numpy array to a torch tensor.
y = torch.from_numpy(x)
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

Let's verify that the numpy array and torch tensor have similar data types.

In [ ]:
x.dtype, y.dtype

(dtype('float64'), torch.float64)

We can convert a PyTorch tensor to a Numpy array using the `.numpy` method of a tensor.

In [ ]:
# Convert a torch tensor to a numpy array
z = y.numpy()
z

array([[1., 2.],
       [3., 4.]])

The interoperability between PyTorch and Numpy is really important because most datasets you'll work with will likely be read and preprocessed as Numpy arrays.